// react-front/web-api-front/src/App.js
import './App.css';
import { BrowserRouter as Router, Route, Routes, Link } from 'react-router-dom';
import UserComponent from './components/UserComponent';
import RoleComponent from './components/RoleComponent';
import RequestStatusComponent from './components/RequestStatusComponent';
import PaymentComponent from './components/PaymentComponent';
import CreditTypeComponent from './components/CreditTypeComponent';
import CreditRequestComponent from './components/CreditRequestComponent';
import CreditComponent from './components/CreditComponent';
function App() {
    return (
      <Router>
      <div className="App">
        <header className="App-header">
          <nav className="navbar navbar-expand-lg navbar-light bg-light">
            <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div className="navbar-nav d-flex justify-content-between w-100">
                <Link className="nav-item nav-link active" to="/api/users">Users<span className="sr-only"></span></Link>
                <Link className="nav-item nav-link" to="/api/roles">Roles</Link>
                <Link className="nav-item nav-link" to="/api/request_statuses">Request Statuses</Link>
                <Link className="nav-item nav-link" to="/api/payments">Payments</Link>
                <Link className="nav-item nav-link" to="/api/credit_type">Credit Types</Link>
                <Link className="nav-item nav-link" to="/api/credit_requests">Credit Requests</Link>
                <Link className="nav-item nav-link" to="/api/credits">Credits</Link>
              </div>
            </div>
          </nav>
        </header>

        <Routes>
          <Route path="/api/users/*" element={<UserComponent />} />
          <Route path="/api/roles" element={<RoleComponent />} />
          <Route path="/api/request_statuses" element={<RequestStatusComponent />} />
          <Route path="/api/payments" element={<PaymentComponent />} />
          <Route path="/api/credit_type" element={<CreditTypeComponent />} />
          <Route path="/api/credit_requests" element={<CreditRequestComponent />} />
          <Route path="/api/credits" element={<CreditComponent />} />
        </Routes>
      </div>
    </Router>
  );
}

export default App;

// angular-front/web-api/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, FontAwesomeModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})

export class AppComponent {
  title = 'Angular App';
}

<header class="App-header">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav d-flex justify-content-between w-100">
        <a class="nav-item nav-link active" routerLink="/api/users">Users<span
          class="sr-only"></span></a>
        <a class="nav-item nav-link" routerLink="/api/roles">Roles</a>
        <a class="nav-item nav-link" routerLink="/api/request_statuses">Request Statuses</a>
        <a class="nav-item nav-link" routerLink="/api/payments">Payments</a>
        <a class="nav-item nav-link" routerLink="/api/credit_type">Credit Types</a>
        <a class="nav-item nav-link" routerLink="/api/credit_requests">Credit Requests</a>
        <a class="nav-item nav-link" routerLink="/api/credits">Credits</a>
      </div>
    </div>
  </nav>
</header>

<main class="App">
  <div class="content">

  </div>

  <router-outlet />
</main>
